import React from 'react';
import SEO from '../components/SEO';

const Legal: React.FC = () => {
  return (
    <>
      <SEO
        title="Legal Disclaimer - InvoiceCore Hub | Important Notices"
        description="Important legal disclaimers for InvoiceCore Hub. Not a law firm. All documents provided for informational purposes only."
        keywords="legal disclaimer, not legal advice, informational purposes, disclaimer, invoice legal disclaimer, free invoice legal, invoice, free invoice, digital invoice"
        type="website"
      />
      <div className="bg-white dark:bg-slate-900 min-h-screen py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <h1 className="text-4xl font-extrabold text-slate-900 dark:text-white mb-4">Legal Disclaimer</h1>
          <p className="text-slate-600 dark:text-slate-400 mb-12">Last Updated: December 21, 2025</p>

          <div className="prose prose-slate dark:prose-invert max-w-none space-y-8">
            <section className="p-6 bg-red-50 dark:bg-red-900/20 border-l-4 border-red-600 rounded-r">
              <h2 className="text-2xl font-bold text-red-900 dark:text-red-200 mt-0">⚠️ Critical Legal Notice</h2>
              <p className="text-slate-900 dark:text-slate-100 font-semibold">
                InvoiceCore Hub is NOT a law firm and does NOT provide legal services, legal advice, or any form of professional consultation. All information, documents, templates, and tools provided on this website are for general informational and educational purposes only.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8 mb-4">1. No Attorney-Client Relationship</h2>
              <p>
                By using InvoiceCore Hub, you understand and agree that:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>No attorney-client relationship is established between you and InvoiceCore Hub</li>
                <li>We are not providing legal advice in any form</li>
                <li>We are not your lawyer and cannot represent you</li>
                <li>Communications between you and InvoiceCore Hub are not confidential or privileged</li>
                <li>You should not rely on any information from our Services as legal advice</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8 mb-4">2. Documents Are Templates Only</h2>
              <p>
                All documents generated through InvoiceCore Hub are templates and samples created for informational purposes only. These documents:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>May not be appropriate for your specific situation</li>
                <li>May not comply with the laws of your jurisdiction</li>
                <li>May not be legally binding or enforceable</li>
                <li>Are not customized legal documents</li>
                <li>Should not be used without professional legal review</li>
                <li>May require modifications to be suitable for your needs</li>
              </ul>
              <p>
                <strong>Using any document generated by InvoiceCore Hub without professional legal review is done entirely at your own risk.</strong>
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8 mb-4">3. Laws Vary by Jurisdiction</h2>
              <p>
                Different jurisdictions have different legal requirements and laws. What is legal in one state or country may be:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Illegal in another jurisdiction</li>
                <li>Inadequate for your specific needs</li>
                <li>Outdated or no longer enforceable</li>
                <li>Subject to recent changes you may not be aware of</li>
              </ul>
              <p>
                InvoiceCore Hub cannot guarantee that any document complies with the laws applicable to your location or situation.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8 mb-4">4. Professional Consultation Required</h2>
              <p>
                <strong>IMPORTANT:</strong> Before using any document generated through InvoiceCore Hub, especially for important legal or business matters, you should:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Consult with a qualified attorney licensed in your jurisdiction</li>
                <li>Have a tax professional review any financial documents</li>
                <li>Have a business advisor review business-related documents</li>
                <li>Ensure the document complies with applicable laws</li>
                <li>Verify the document is appropriate for your specific situation</li>
              </ul>
              <p>
                The cost of professional consultation is minimal compared to the potential consequences of using an improper or invalid document.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8 mb-4">5. No Accuracy Guarantee</h2>
              <p>
                We do not guarantee the accuracy, completeness, or correctness of any information or documents provided through InvoiceCore Hub. While we strive to provide accurate and helpful information:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Errors or omissions may exist</li>
                <li>Information may become outdated</li>
                <li>Calculations may be incorrect</li>
                <li>Documents may not meet your specific needs</li>
                <li>We provide no warranty of fitness for any particular purpose</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8 mb-4">6. No Liability for Consequences</h2>
              <p>
                InvoiceCore Hub is not responsible for:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Any legal consequences of using our documents</li>
                <li>Damages resulting from reliance on information provided</li>
                <li>Loss of business, revenue, or opportunity</li>
                <li>Disputes or litigation arising from documents you generate</li>
                <li>Regulatory fines or penalties</li>
                <li>Any other damages, direct or indirect</li>
              </ul>
              <p>
                <strong>You assume all responsibility and risk for any use of documents, templates, or information from InvoiceCore Hub.</strong>
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8 mb-4">7. Not a Tax, Financial, or Business Advisor</h2>
              <p>
                InvoiceCore Hub does not provide tax advice, accounting advice, financial advice, or business consultation. Information about:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Tax obligations and liabilities</li>
                <li>Financial planning and strategy</li>
                <li>Business structure and formation</li>
                <li>Accounting practices and reporting</li>
              </ul>
              <p>
                ...should only be obtained from qualified professionals such as CPAs, tax attorneys, financial advisors, and business consultants.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8 mb-4">8. AI-Generated Content</h2>
              <p>
                For tools that use artificial intelligence (such as Google Gemini API):
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>AI-generated content may contain errors or inaccuracies</li>
                <li>AI may misunderstand your requirements</li>
                <li>AI-generated documents are not reviewed by human experts</li>
                <li>You are responsible for reviewing and verifying all AI output</li>
                <li>We make no warranty regarding the quality or accuracy of AI-generated content</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8 mb-4">9. Modification and Accuracy</h2>
              <p>
                Our documents and information are provided "AS IS" without modification or guarantee. We do not:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Monitor changes in laws or regulations</li>
                <li>Automatically update documents when laws change</li>
                <li>Provide notice of changes in legal requirements</li>
                <li>Verify the accuracy of generated documents</li>
                <li>Ensure compliance with current laws</li>
              </ul>
              <p>
                It is your responsibility to ensure any document is current and compliant with applicable laws.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8 mb-4">10. Dispute Disclaimers</h2>
              <p>
                If a document you generate through InvoiceCore Hub becomes subject to dispute or litigation:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>InvoiceCore Hub is not responsible for defending the document</li>
                <li>We will not provide legal representation</li>
                <li>We are not liable for the outcome of any dispute</li>
                <li>You are solely responsible for costs of dispute resolution</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8 mb-4">11. Specific Disclaimer: Contracts and Agreements</h2>
              <p>
                For contracts, employment agreements, service agreements, and other binding documents:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>These documents must be reviewed by an attorney before use</li>
                <li>Templates may not include necessary clauses for your situation</li>
                <li>Documents may not adequately protect your interests</li>
                <li>Failure to have legal review could result in serious financial consequences</li>
                <li>We are not responsible if a contract is found to be unenforceable</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8 mb-4">12. Specific Disclaimer: Invoices and Financial Documents</h2>
              <p>
                For invoices, financial statements, and accounting documents:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>These documents are templates and may not comply with accounting standards</li>
                <li>Financial information should be verified with your accountant</li>
                <li>Tax implications should be reviewed by a tax professional</li>
                <li>Calculations should be verified independently</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8 mb-4">13. Links to External Resources</h2>
              <p>
                InvoiceCore Hub may link to external legal resources, government websites, or third-party services. We do not:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Endorse any external services or information</li>
                <li>Verify the accuracy of external information</li>
                <li>Guarantee the continued availability of linked resources</li>
                <li>Take responsibility for third-party content</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8 mb-4">14. Service Availability</h2>
              <p>
                InvoiceCore Hub is provided on an "AS IS" and "AS AVAILABLE" basis. We do not guarantee:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Continuous availability of the service</li>
                <li>Error-free operation</li>
                <li>Data security or privacy</li>
                <li>Preservation of documents you create</li>
              </ul>
              <p>
                You are responsible for maintaining backup copies of any important documents.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8 mb-4">15. When to Consult an Attorney</h2>
              <p>
                You should definitely consult an attorney if:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Creating a legal contract or agreement</li>
                <li>Forming a business entity (LLC, Corporation, Partnership)</li>
                <li>Dealing with employee/contractor relationships</li>
                <li>Creating intellectual property or trademark documents</li>
                <li>Dealing with real estate or property matters</li>
                <li>Creating a will, trust, or estate plan</li>
                <li>Involved in any litigation or dispute</li>
                <li>Dealing with immigration or visa matters</li>
                <li>Creating documents with significant financial implications</li>
                <li>Uncertain about legal requirements in your jurisdiction</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8 mb-4">16. Finding Legal Help</h2>
              <p>
                If you need professional legal assistance, consider:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li><strong>State Bar Associations:</strong> Search for licensed attorneys in your state</li>
                <li><strong>Legal Aid Services:</strong> For low-income individuals</li>
                <li><strong>Online Legal Services:</strong> Like LegalZoom or Rocket Lawyer for affordable document review</li>
                <li><strong>Law School Clinics:</strong> Many law schools offer free legal services to the public</li>
                <li><strong>Local Bar Referral Services:</strong> Most states have lawyer referral services</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8 mb-4">17. Assumption of Risk</h2>
              <p>
                <strong>By using InvoiceCore Hub, you acknowledge and assume full responsibility and risk for:</strong>
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>All information obtained through our Services</li>
                <li>All documents generated using our tools</li>
                <li>All decisions made based on information from our Services</li>
                <li>Any consequences resulting from use of our Services</li>
                <li>Legal, financial, or business outcomes related to our documents</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8 mb-4">18. No Warranty Disclaimer</h2>
              <p>
                InvoiceCore Hub IS PROVIDED ON AN "AS IS" BASIS WITHOUT ANY WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO:
              </p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>WARRANTIES OF MERCHANTABILITY</li>
                <li>WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE</li>
                <li>WARRANTIES OF ACCURACY OR COMPLETENESS</li>
                <li>WARRANTIES OF LEGALITY OR ENFORCEABILITY</li>
                <li>WARRANTIES AGAINST INFRINGEMENT</li>
                <li>WARRANTIES OF TITLE OR OWNERSHIP</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8 mb-4">19. Agreement to Disclaimer</h2>
              <p>
                If you do not agree with this Legal Disclaimer, you should not use InvoiceCore Hub. Continued use of our Services constitutes your agreement to all terms in this disclaimer.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-slate-900 dark:text-white mt-8 mb-4">20. Changes to Disclaimer</h2>
              <p>
                We may update this Legal Disclaimer at any time. Your continued use of InvoiceCore Hub following any updates indicates your acceptance of the revised disclaimer.
              </p>
            </section>

            <section>
              <div className="mt-12 p-8 bg-slate-100 dark:bg-slate-800 rounded-lg">
                <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-6">Contact Information</h2>
                <p className="mb-4">
                  If you have questions about this Legal Disclaimer or need to report concerns:
                </p>
                <div className="space-y-3">
                  <p className="text-slate-900 dark:text-white">
                    <strong>InvoiceCore Hub Legal Team</strong>
                  </p>
                  <p className="text-slate-700 dark:text-slate-300">
                    📧 Email: legal@invoicecorehub.com
                  </p>
                  <p className="text-slate-700 dark:text-slate-300">
                    📧 Support: support@invoicecorehub.com
                  </p>

                </div>
              </div>
            </section>

            <section>
              <div className="mt-8 p-6 bg-amber-50 dark:bg-amber-900/20 border-l-4 border-amber-600 rounded-r">
                <p className="text-slate-900 dark:text-white text-center font-bold text-lg">
                  Remember: These are templates and tools for informational purposes only.
                  <br />
                  <span className="text-amber-700 dark:text-amber-300">Always consult with qualified professionals before making important legal or business decisions.</span>
                </p>
              </div>
            </section>
          </div>
        </div>
      </div>
    </>
  );
};

export default Legal;
